spring:
  profiles: container
  datasource:
    url: jdbc:mysql://mysql:3306/userManagement?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345678
    initialize: true
